services:
  app:
    build: .
    container_name: bankslip_app
    command: sh -c "yarn prisma generate && yarn prisma migrate deploy && yarn start"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - db
      - redis
    env_file:
      - .env
    ports:
      - '${APP_PORT}:3000'
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/bankslip_db
      - RABBITMQ_URL=amqp://rabbitmq
      - REDIS_HOST=redis

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  db:
    image: postgres
    container_name: postgres_db
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankslip_db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
